---
title: "supply_chain"
author: "Gibran Makyanie"
date: "03/03/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(gridExtra)
```

```{r}
sc <- read_csv('supply_chain_data.csv')

sc$allowable_increase_norm <- (((sc$allowable_increase / sc$demand) - 1 )* 100)
sc$allowable_decrease_norm <- (((sc$allowable_decrease / sc$demand) - 1 )* 100)
sc$demand_norm <- 0
sc_3 <- sc %>%
  filter(year <= 3)


sp <- read_csv('shadow_price.csv') %>%
  arrange(desc(shadow_price_real)) %>%
  mutate(shadow_price_real = shadow_price_real/1000)

cost <- read_csv('cost_overall.csv')

cost10 <- cost %>% filter(npv == 10)
cost4.18 <- cost %>% filter(npv == 4.18)

demand <- read_csv('total_demand.csv')

further <- read_csv('cost_further.csv')

```

```{r}

grid.arrange(
ggplot(sc_3, aes(x=year, col=distribution_centre, fill=distribution_centre,y=demand)) + 
    geom_line() +
    ylim(0,125) + 
    scale_x_continuous(breaks=seq(1, 3, 1)) +
    labs(y="Demand (million liters)", x="Year"),
ggplot(sc_3, aes(x=year, col=distribution_centre, fill=distribution_centre,y=demand_norm, ymin=allowable_decrease_norm, ymax=allowable_increase_norm)) + 
    geom_ribbon(alpha = 0.5) + 
    geom_line() + 
    facet_grid(cols = vars(distribution_centre)) +
    ylim(-150, 150) +
    scale_x_continuous(breaks=seq(1, 3, 1)) +
    labs(y="Difference with actual demand (%)", x="Year"))
```


```{r}
sp %>%
  arrange(shadow_price_real) %>%    # First sort by val. This sort the dataframe but NOT the factor levels
  mutate(distribution_centre=factor(distribution_centre, levels=distribution_centre)) %>%# This trick update the factor levels
  mutate(price = round(shadow_price_real,2)) %>% 
  ggplot(aes(x=distribution_centre, y = shadow_price_real )) + geom_col() + coord_flip() +
      labs(y="Shadow Price (in thousands $)", x="Distribution Centre") +
      geom_text(aes(label=price, y=price + 2.9), position=position_dodge(width=0), size=5)



further %>%
  arrange(cost) %>%    # First sort by val. This sort the dataframe but NOT the factor levels
  mutate(distribution_centre=factor(distribution_centre, levels=distribution_centre)) %>%   # This trick update the factor levels
ggplot(aes(x=distribution_centre, y = cost )) + geom_col() + coord_flip() +
      labs(y="Shadow Price (in thousands $)", x="Distribution Centre", subtitle = 'Outside the allowable range of capacity change') 
```


```{r}

ggplot(cost, aes(x = year, y = cost, fill = category)) + geom_bar(stat = "identity") +
  labs(x = 'Year', y = 'Cost (million $)')
```



```{r}

grid.arrange(
ggplot(demand, aes(x=year, y=total_demand)) + 
    geom_line()  +
    geom_hline(yintercept = 440, lty=2, color='#DC143C') +
  geom_hline(yintercept = 525, lty=2, color='#008080') +
    labs(y="Total Demand (million liters)", x="Year") +
    xlim(1,20) +
    ylim(400,550),
ggplot(cost4.18, aes(x = year, y = cost, fill = category)) + geom_bar(stat = "identity") +
  labs(x = 'Year', y = 'Cost (million $)')
)
```

